--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.338.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 15/05/2023 10:51:15 CH
-- Server version: 8.0.32
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE database_datn;

--
-- Drop table `users`
--
DROP TABLE IF EXISTS users;

--
-- Set default database
--
USE database_datn;

--
-- Create table `users`
--
CREATE TABLE users (
  id char(36) NOT NULL,
  fullName varchar(255) NOT NULL DEFAULT '',
  password varchar(255) NOT NULL DEFAULT '',
  email varchar(50) NOT NULL DEFAULT '',
  address varchar(255) DEFAULT NULL,
  phoneNumber varchar(20) DEFAULT NULL,
  roleId varchar(50) DEFAULT NULL,
  gender varchar(20) DEFAULT NULL,
  avatar varchar(255) DEFAULT NULL,
  createAt datetime DEFAULT NULL,
  updateAt datetime DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 409,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci,
COMMENT = 'Bảng người dùng';

-- 
-- Dumping data for table users
--
INSERT INTO users VALUES
('11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', 'Phạm Tuấn Trung', 'iHOktgBSJ10T4B4hFT1qDg==', 'Sidney_Agnew3@nowhere.com', 'Thái Bình', '0984496315', 'R3', 'Nam', 'R7', '1988-01-18 19:15:47', '1971-05-01 05:36:24'),
('1152da18-24d8-65b6-0380-e8e2a817c80e', 'Dương An Tâm', 'NBsc/ceNuc911WuFNYRn9Q==', 'Ted.Mace49@example.com', 'Bình Dương', '0986599879', 'R3', 'Nam', 'P', '1995-10-17 14:40:28', '1970-01-01 00:05:07'),
('119af01c-406e-1565-a77d-e8c757976496', 'Hồ Nam Phi', 'HuzoddNgdGYdb59GEjxixw==', 'Pasquale.Autry449@example.com', 'Bình Dương', '0982688505', 'R1', 'Nam', 'PPH49V4464B7JG7751069UZ0W9QR6VV63XG6Q2BSCA55PP', '1970-01-01 00:01:31', '1970-01-01 02:16:16'),
('11f7089b-33e6-371a-f817-7000f455f3d5', 'Đặng Tuấn Tú', 'mjeaBCGGPpdRohsBoFcicA==', 'jajk3595@example.com', 'Hải Dương', '0983548082', 'R1', 'Nữ', '6JXJIE33671X1', '1986-03-26 05:45:26', '1970-01-01 02:09:09'),
('124b4a06-7d39-6835-0980-e8e2a817c80e', 'Lê Thiên Mai', 'j7PzSRxkcJc4rYzC4c6OzQ==', 'ArnettaShuler721@example.com', 'Hà Giang', '0987729500', 'R2', 'Nam', 'H3F26MKY81Y43MH5QTYT2HBCM567P365CPTAAB3W6V6J7H8OIAE5DYUB', '2011-04-13 08:44:07', '1986-08-06 16:25:20'),
('135e72be-6cdf-5311-a47d-e8c757976496', 'Huỳnh Ái Thy', 'yC4+tS1EPenfcIDbY13q2w==', 'ArmandoMaher7@nowhere.com', 'Hà Giang', '0986001642', 'R3', 'Nam', 'FN7N2OZBOLP5YZK8', '2010-02-28 04:43:39', '1987-11-22 21:58:45'),
('13fc3540-52b5-3489-1163-eeb1d8ed8cef', 'Bùi An Tâm', 'wl5AuhtZKv3jWmFkwbptZw==', 'Tessie_Sommers@example.com', 'Hà Giang', '0982967524', 'R1', 'Nữ', 'I57GWT87HL245S47T89E4F9TQJW005C2GP44G', '1970-01-01 00:55:33', '2006-09-17 21:27:37'),
('141eea25-7b62-62de-8832-6a1673ffca7c', 'Phạm Tuyền Lâm', 'LBxk8DyXr+bdvkweWQKHLA==', 'Abreu6@nowhere.com', NULL, NULL, 'R1', NULL, NULL, NULL, '1987-04-03 00:39:09'),
('142cb08f-7c31-21fa-8e90-67245e8b283e', 'Nguyễn Khoa Trưởng', 'RMJelfmTrQMhVGTTUaUW5A==', 'Bolt@nowhere.com', 'Bình Dương', '0980460192', 'R1', 'Nam', '00A848KWUQ74', '1970-01-01 00:07:13', '1970-01-01 00:00:04'),
('142f0fed-2a8d-534c-1180-e8e2a817c80e', 'Dương Thiện Mỹ', 'u/3faSSWN3g3hJaW3/175g==', 'ParisK.Werner@example.com', 'Bình Dương', '0987027590', 'R3', 'Nam', '0OHPBK3J76XPY9L4T6V3LBLJKRFDG391J9620865574W8KEO7X652', '1970-01-01 00:02:18', '1971-10-23 14:44:30'),
('14672f47-7abc-2316-a97d-e8c757976496', 'Lê Bích Hợp', '7j6KUyHvTbTVXNsVUeU+Lw==', 'CordieAbrams@example.com', 'Ninh Bình', '0985520245', 'R2', 'Nam', 'B', '2017-04-26 00:36:27', '1970-01-01 00:04:16'),
('14c0ce35-1687-459c-1acb-66948daf6128', 'Dương Việt Cường', 'TlVBsWzM39vZQqVwr2aQoQ==', 'MathewDeal16@example.com', 'Bình Dương', '0980236884', 'R1', 'Nam', 'HG4VX7L5HK9MB', '1970-01-01 00:01:38', '2007-10-29 22:10:42'),
('156a4794-7a9b-5c3e-2bcb-66948daf6128', 'Võ Vân Quyên', '9hKkZGU3vByu231fLVlFXA==', 'Ahmed@example.com', 'Bình Dương', '0986935075', 'R3', 'Nam', '5K642274YPHE59X04TF44E', '1971-04-05 22:26:45', '2005-06-07 20:01:37'),
('15fb79ad-271b-30eb-8f32-6a1673ffca7c', 'Lê Tâm Trang', 'z+g5WRlHxGjI1nFFtSa5Rw==', 'Isabel.Abernathy186@example.com', 'Bình Dương', '0986816715', 'R3', 'Nữ', '3712IN2UNQW12A0M55SRKG', '2013-06-08 09:12:04', '2002-04-12 18:00:09'),
('16d64573-7d44-18a4-2acb-66948daf6128', 'Bùi Viễn Thông', 'S9L8kaIRdr23h7camZDKaQ==', 'Amato@example.com', 'Bình Dương', '0987766548', 'R2', 'Nữ', '8L12V7GYZLAT943I0I3T', '1984-12-02 07:33:16', '1970-01-01 00:00:09'),
('17120d02-6ab5-3e43-18cb-66948daf6128', 'Ngô Ngọc Cảnh', 'V4nE+4PqWuTQW67ttUnOSw==', 'Bray162@example.com', 'Quảng Ninh', '0981674786', 'R3', 'Nam', '7T', '1974-04-28 07:44:36', '1996-03-24 08:57:27'),
('176a5ef0-6a1f-5178-7292-08c864661f9c', 'Phạm Bảo Lễ', 'o+0lgU3ibDqJWrurXXSBgg==', 'wpwrzbcx.kdqf@example.com', 'Bình Dương', '0983063109', 'R3', 'Nam', 'SHV20L53WML85H7789186RPNBOI0AS707MQZ3UPY13VR376H52715B6LJ76GJ2MESENQ8', '1970-11-10 14:44:36', '1975-06-11 03:08:52'),
('1785d6d7-5898-2235-a17d-e8c757976496', 'Dương Kim Toàn', '1rttBpazUFb/XTKsRc50Gw==', 'Andre.ADorman161@nowhere.com', 'Thái Bình', '0986064132', 'R3', 'Nam', 'JP3286G8L1210V0A3', '1975-02-14 03:10:16', '1993-07-31 22:24:40'),
('179d5bc0-2405-67f7-9590-67245e8b283e', 'Trần Minh Yến', 'iGlu2obO4QRlkVqZE3/btw==', 'TraciCloud@nowhere.com', 'Thái Bình', '0989891517', 'R1', 'Nam', '30SWCC8V88B8MH2CJR43KK1BZ00Y9770L', '1985-07-09 23:50:50', '2020-05-09 02:40:35'),
('17bf02de-2b93-2829-29cb-66948daf6128', 'Lê Quang Danh', '7xktzRXWAnNihGHfwcUvBA==', 'EllisFranks43@example.com', 'Hải Dương', '0986920958', 'R2', 'Nữ', 'I4R02DNS1Y4BN', '1996-10-25 09:05:28', '1985-05-04 23:02:17'),
('1b053175-548d-6448-8bdd-867949feb8b5', 'Bùi Xuyến Chi', '2/QSacAptb3zFtT043mLGw==', 'AshleyRice@example.com', 'Bình Dương', '0985401744', 'R2', 'Nam', '1HS3S4TG407LZB8432W9V', '2014-07-28 16:47:35', '2014-02-25 04:10:40'),
('1b336f56-7ee3-7ceb-1ccb-66948daf6128', 'Trần Cát Tường', '1ZYfvz8yg96Vk/USNj/0bA==', 'Hairston5@example.com', 'Quảng Ninh', '0989574685', 'R1', 'Nam', '3738SMMB1TBW35X61H0Z2U4228H28', '1970-01-01 00:04:31', '1970-01-01 00:00:18'),
('1bf8a43c-47fb-4d6c-1863-eeb1d8ed8cef', 'Phan An Cơ', 'rJPKr+/7LVuBU3bjWzGIeg==', 'DevonPBoren2@example.com', 'Thái Bình', '0987069327', 'R3', 'Nữ', 'Z50VQ0WIW0VP0IV5B', '2017-10-30 13:43:58', '2008-12-26 16:18:56'),
('1c2187a3-6d94-2ded-21cb-66948daf6128', 'Đặng im Quyên', 'b/JpxvKB69/1uvNPZhw8oA==', 'JenaeMarcum651@example.com', 'Hà Nội', '0988777217', 'R1', 'Nữ', '6078C03F45P5VN5JV3I2EML51OA0C8288SQLR56MFKM15R5D6L17WO7S2X151U9GS0001647W0R2V', '1970-03-03 05:10:23', '2017-08-20 14:20:13'),
('1da031ce-7347-6fc1-ff17-7000f455f3d5', 'Phạm Việt Dũng', 'pT5Zd9yFj9tVlmNiZBS/lA==', 'kbwzgarj.bcvnyk@example.com', 'Hà Giang', '0980334509', 'R1', 'Nữ', '4', '1986-09-24 11:00:21', '1970-01-01 01:25:02'),
('1ded3dd7-32db-5bc9-9190-67245e8b283e', 'Võ Công Tráng', '1ipjVDQAJ+ooRn9NrkRj2Q==', 'ikzv7@nowhere.com', 'Thái Bình', '0988582048', 'R2', 'Nam', '3PY16307K25D', '2001-04-07 10:38:53', '2018-10-12 11:19:55'),
('1e5a953f-1c88-5769-addb-e5d54223c257', 'Đặng Bảo Phương', 'TC2/ncWZOkbz3cMhOZh0Dw==', 'Erick.O.Altman@example.com', 'Bình Dương', '0981146038', 'R3', 'Nam', 'G51', '2004-12-05 17:54:40', '1991-11-24 05:43:46'),
('1eb07f4e-7018-6d54-6b92-08c864661f9c', 'Nguyễn hải Ca', 'bfwP27BrVvJ9JqmGaOeUFw==', 'Orlando@example.com', NULL, NULL, 'R3', NULL, NULL, NULL, '2007-01-31 08:08:20'),
('1f22399e-14b4-5c2b-8132-6a1673ffca7c', 'Bùi Công Tuấn', 'vP7eGDSozS9n5HAiiMv1EQ==', 'LakeeshaAbel8@example.com', 'Quảng Ninh', '0982437058', 'R2', 'Nữ', '1220PL0V7Y5SZAGF67PR517DSX9GK6D366HMZWUOJB4ND1NLQD83TF2NY', '2008-09-16 15:39:51', '1989-08-09 19:29:07'),
('1f74cd3f-6de4-5324-0180-e8e2a817c80e', 'Huỳnh Huy Chiểu', 'z04t3ztjbz9olh0bsx7Vzw==', 'NathanielC_Christman823@example.com', 'Bình Dương', '0985593201', 'R1', 'Nam', 'BTL8K336H77098SW059MTLU9GK4S1L5G7H7S98M8869BV27SS4335I0530I8LW73NN103P', '1970-01-01 00:00:05', '1970-01-01 00:56:40'),
('1f8d7e46-1d1e-335f-79dd-867949feb8b5', 'Võ Uy Vũ', 'wW18t/u64mzFXmFLUKUawg==', 'Tenisha_Mcclintock@nowhere.com', 'Hà Nội', '0985584987', 'R1', 'Nam', 'B7DEQACWB5S9G8U342G5619474919313O27630', '1974-05-19 14:31:01', '1993-11-09 06:41:13'),
('205a3e0a-13fe-3557-8232-6a1673ffca7c', 'Dương Minh Khuê', 'u6uX0Q1tYNK2GiAsYEOk0A==', 'Alley91@example.com', NULL, NULL, 'R1', NULL, NULL, NULL, '1992-02-14 22:49:59'),
('207bba19-49aa-63f4-88dd-867949feb8b5', 'Ngô Trà My', '8k+yuPcohUHAFA/H/rp9uQ==', 'Adena.Abbott966@example.com', 'Hà Nội', '0984710405', 'R2', 'Nam', '60I9YX620759332EJ623DL6VS965U9LZX71N2', '1993-01-21 23:49:02', '1970-01-01 00:00:52'),
('20d0b9f3-3e65-1639-9d7d-e8c757976496', 'Huỳnh Anh Chi', 'IAzs2bjD89FAL9S7KWGhWg==', 'Darrell_Mcintyre21@example.com', 'Hải Dương', '0982093111', 'R2', 'Nam', '6T8OH20F9ZV1I3269DTH76BXJ22M3656K', '1970-01-01 00:13:11', '2019-12-30 06:48:02'),
('2152ea1c-3cd9-7d2b-8d32-6a1673ffca7c', 'Bùi An Ninh', 'jnGGZo4WkxcOGyAJUuw4YA==', 'Tristan_Castle@nowhere.com', 'Hải Dương', '0988191940', 'R3', 'Nam', 'EK6S9E3WQ292MP6F2EF1', '1985-10-30 01:14:09', NULL),
('22032557-51a3-4005-1263-eeb1d8ed8cef', 'Dương Việt Anh', '0NBpFyOLYPjsuUlNFLyJiA==', 'Weston34@nowhere.com', 'Hải Dương', '0982324472', 'R2', 'Nam', 'LP1T58D18H20C1D6L240IZQT2AF094S0LU0OR61AQ1D395HQ7335A40JZ5797CMW9JJ41JG5PYMCCUK3WKDU09R2S2Z702PL5VO997085D5VZ4477A2857YPJ8XK1LC4C9659V9K4JP', '1970-01-01 00:00:38', NULL),
('22f831e3-5d4e-3508-1480-e8e2a817c80e', 'Dương Công Bằng', 'H7EN8j03HOb1zPt3pP2wsA==', 'BethOliveira511@nowhere.com', 'Ninh Bình', '0983400318', 'R2', 'Nam', 'Z9PLOP5H5SST404WH', '1970-01-01 02:16:51', '2012-12-16 15:25:57'),
('24629593-3d34-32fd-997d-e8c757976496', 'Võ Thúy Ngà', 'KuMTt3ewJzkt/N20kGlttw==', 'OdellG752@example.com', 'Hà Nội', '0985569884', 'R1', 'Nam', '1446AH1PC228921LT0892EZWC9L46M6', '1970-01-01 00:01:28', '2015-03-20 10:20:37'),
('247986de-4165-651a-9490-67245e8b283e', 'Phạm Việt Hồng', 'Og2HXSypw0EAlQfQ7n1nsg==', 'Adolph.Antoine@example.com', 'Bình Dương', '0982388139', 'R1', 'Nam', 'C6432RI1U79A0T9Q9HQHB9N79FQ1BCA587XC6QNELA45272SM3', '1980-12-16 18:08:49', '1987-05-31 22:14:14'),
('2508b8b3-3851-6ae9-86dd-867949feb8b5', 'Hồ An Nam', 'PGQ/xx1aWgQOASxNgUzrjA==', 'Dugas@example.com', 'Hà Giang', '0981616971', 'R3', 'Nam', '171O8V7NK0C7UER9LWGK3', '1999-08-25 14:40:22', '1970-01-01 00:06:29'),
('257ea484-501b-1644-7cdd-867949feb8b5', 'Hồ Bích Ðiệp', 'Lq60OtVo34xiGP3UcyDPOA==', 'KaterineHinojosa@example.com', 'Bình Dương', '0985646761', 'R2', 'Nam', 'P510IRGOX9140WI5R597S3HMFB9AVBT65W30', '1990-04-09 00:49:29', '1997-04-23 18:32:11'),
('258eee01-5e19-7ac4-2ccb-66948daf6128', 'Dương Tâm Trang', 'pGw7VPLJhxzYHa96kySZwA==', 'Freedman@example.com', 'Ninh Bình', '0983458127', 'R1', 'Nam', 'F148EE85V04GZN04G17JD9ZAO', '1970-01-01 00:00:37', '1977-12-16 15:37:37'),
('25efaa0a-2220-4655-20cb-66948daf6128', 'Võ Minh Quân', 'nn0UJqryvBVbEpuUJdfSOQ==', 'JuleneDasilva@example.com', 'Bình Dương', '0988638491', 'R3', 'Nữ', '8S7LIC2Q83VDX22W8D135FR0LWH6MPF37', '2008-03-09 23:44:49', '1984-04-02 08:35:04'),
('276e9765-4c6a-4239-0b80-e8e2a817c80e', 'Lê Vương Triều', 'PGKV82xok6TItH2ciBTbEg==', 'Crane@nowhere.com', 'Ninh Bình', '0980026014', 'R1', 'Nữ', '51', '1974-11-24 15:35:37', '1982-08-29 15:37:38'),
('27a76ea6-6309-6d6a-0218-7000f455f3d5', 'Nguyễn Bích Trâm', 'YHoqYJF4hS/WDMAvP5LAXQ==', 'AdriaX.Ainsworth784@example.com', 'Thái Bình', '0989004737', 'R1', 'Nữ', 'GR8J5RCI', '2008-03-16 20:37:18', '1970-01-01 00:12:58'),
('27e293c1-483b-5599-a090-67245e8b283e', 'Huỳnh Thanh Tùng', '8A8RwmyCoFG3tOFx+ZkjnA==', 'Pettigrew442@nowhere.com', 'Hải Dương', '0984456965', 'R3', 'Nữ', 'E6X83H2M9P7H2M1RR', '1970-01-01 00:00:26', '1970-01-01 00:00:38'),
('284ccb05-337b-7e6f-9090-67245e8b283e', 'Đặng Ðan Khanh', 'wdxFfoOnNw/HY7Q2GiXKUw==', 'SmalleyS@nowhere.com', 'Quảng Ninh', '0985976086', 'R3', 'Nữ', '0K497DCR6OD39KL1UO0UKYP6EAYX81HP58SXI1W66OIN82PZ672ZD41GMFJ5X131S5E68A803V45F97UC0PS35C8V922V59AHM56FC3B923FMSKZQRX', '1998-02-04 15:57:17', '1970-01-01 00:00:25'),
('28e5fd74-7c2e-6105-26cb-66948daf6128', 'Huỳnh Diệu Loan', 'O6HCsw8VUdrpnXl2zec/Lg==', 'KrystalGooch757@nowhere.com', 'Quảng Ninh', '0983411351', 'R1', 'Nam', '09A9B88Y95J', '1970-01-01 01:33:03', '1970-01-01 00:00:55'),
('2a2516e8-7ca5-62b3-9132-6a1673ffca7c', 'Đặng Bảo Quốc', 'vBjq1qWSoB925oc8PvRnlA==', 'Quigley@nowhere.com', 'Hà Nội', '0982869773', 'R1', 'Nam', 'XV9EU3C357Q75UY6C385C7KTL33922XTX7MJ86V2', '1970-01-01 00:02:44', '2022-05-31 20:10:33'),
('2b850d3d-6722-3f01-1bcb-66948daf6128', 'Dương Bình Dân', 'e8mS/BSQ0sDUB/bQXFioJg==', 'SanfordRivas721@example.com', 'Ninh Bình', '0982471417', 'R3', 'Nữ', '2V4JLQV7247V3J6LV8B3T9Q5KCBTPM9X2I26706L44J19GEK459699YX9M0NLLEU86CS1L3TE5SZ899A0S24Q6CX03BGSY', '2004-11-11 20:30:29', '1970-01-01 00:00:13'),
('2bbbd485-6df2-536a-7e32-6a1673ffca7c', 'Võ Giang Lam', '0QPpzU96B17qWXqL6Uezhg==', 'Adler@example.com', 'Hà Giang', '0987210881', 'R2', 'Nữ', '375M54', '1970-01-01 00:01:04', '2004-06-01 11:10:52'),
('2bf413d3-7a2c-217a-78dd-867949feb8b5', 'Phạm Thành Ðệ', 'PitSXEqlOdO4/4z3o4dcQQ==', 'Sturgill@example.com', 'Thái Bình', '0980646899', 'R1', 'Nữ', '2HS3W176X29J36NM8WW0G18K2', '2018-06-28 02:44:43', '1983-07-17 15:15:26'),
('2c4d181d-6dbb-4b03-87dd-867949feb8b5', 'Bùi Ðình Chiểu', 'qIQ08uNrgvu3o3sUog1aJg==', 'Adam_Leal@example.com', 'Hà Nội', '0985476486', 'R3', 'Nam', 'C4X94CM5C06X', '2016-11-28 04:50:46', '2016-09-04 18:49:48'),
('2c7af5cb-448b-1c53-a57d-e8c757976496', 'Huỳnh Anh Khoa', '2k38o8PZMAPLc/WBrTs0zg==', 'Barrios@example.com', 'Hà Nội', '0988981510', 'R2', 'Nam', '46ONTP0R2U99F9ZAJ39SP3C5JC4WAZSC4R66Q67E1TAOXA', '1970-01-01 00:09:53', NULL),
('2d19b0e8-2a06-52dc-a190-67245e8b283e', 'Võ Ân Lai', 'Ge+Hy4vDu+sm3hXIuuRFQw==', 'Adelaida_Crespo5@nowhere.com', 'Quảng Ninh', '0987159644', 'R3', 'Nữ', '5284VGZ20AAVDEH002034569NW08868605NWX36R4W8P6J34176M54N1V0IG4KA0591JKYQ23KKOHVP2STK54U8U7FJ1D7556X3PB05RC5W', '2021-12-06 15:45:07', '1970-01-01 00:53:22'),
('2d558039-6f60-6d55-fd17-7000f455f3d5', 'Hồ An Cơ', 'js5ARzExl6X53umyZuSSpQ==', 'svlh03@example.com', 'Hải Dương', '0983940044', 'R3', 'Nam', '1UNVT4RT365ZJR2N046701I795155CIVJ8', '1970-01-01 00:37:44', '2004-04-07 02:16:34'),
('2dcedb9c-6c32-7d27-977d-e8c757976496', 'Nguyễn Ðức Chính', '1j+4salX3NeRdGGwcKQdiw==', 'AdalineW.Radford8@example.com', 'Hải Dương', '0988900637', 'R1', 'Nữ', '6LNBIK69K942QUZ6N3G7632CLG33C8EE2IX4I0Y', '2000-12-05 11:44:33', '2001-02-22 22:08:53'),
('2de001fe-529b-33ad-0280-e8e2a817c80e', 'Đặng Thanh Xuân', 'GB+9C2t+Ltv36y4k1k/UGA==', 'CierraCheatham@nowhere.com', 'Thái Bình', '0987757955', 'R3', 'Nam', 'A30OLKM537RI1VITOZL0564S6R4O0R372SJ3Y0LO4UV31724PHDL48TPU13Y4M86J018LR1KQ62896IH2E448AH0P53M9', '1982-08-29 00:30:12', '2001-02-21 16:34:56'),
('2fb0b105-7808-503a-76dd-867949feb8b5', 'Dương Phú Bình', 'J2x+SEvDzJXF+ijbdO+hFw==', 'DorcasLadner5@example.com', NULL, NULL, 'R3', NULL, NULL, NULL, '1980-11-22 21:28:54'),
('2fc95768-5570-6429-28cb-66948daf6128', 'Lê Công Tuấn', '3Yyd/jZ9NRvZjPbt/JXZyg==', 'JordonMorrill@nowhere.com', NULL, NULL, 'R2', NULL, NULL, NULL, '1986-10-20 17:07:55'),
('2ff059da-69a9-17a4-fc17-7000f455f3d5', 'Bùi Ðức Tuấn', 'DMnGqR3+/aIJW3ui2lP5jA==', 'bfcv409@example.com', 'Thái Bình', '0986369809', 'R2', 'Nam', '87I8EAI8V72MKF6SL9D7A3ZNP3J30F4PTZ02V77J1H87LL8TLG7L', '1990-02-01 21:03:51', '1970-01-01 00:00:12'),
('30c8ee28-58a3-22f2-5e92-08c864661f9c', 'Hồ Duyên My', 'hBe/AwVWsvKbhgtAn3oNIw==', 'Scarborough@example.com', NULL, NULL, 'R1', NULL, NULL, NULL, '1970-01-01 00:00:04'),
('31584a21-584a-7428-0d80-e8e2a817c80e', 'Bùi Mai Hà', 'FHxN81cGFiTrxZ6MMFOBlg==', 'SamuelVann@example.com', 'Hà Nội', '0983205722', 'R3', 'Nam', '9QJ83', '1970-01-01 01:40:54', '1984-04-11 14:54:12'),
('336f81b7-417d-7e3a-1363-eeb1d8ed8cef', 'Dương Phú Thời', 'Aabd8UEVK2hVG2qECPBkzw==', 'Edwina_Abreu884@nowhere.com', 'Hà Nội', '0987293749', 'R1', 'Nam', 'C4C12GF6QACSHCO2BIE6X228P9UZS2RGVN9N459529DMC06', '1970-01-01 00:00:10', '1970-01-01 00:00:44'),
('33851c36-6445-4680-23cb-66948daf6128', 'Đặng Bích Hợp', 'cfrhQQmaUt6KUp9rkg5v3g==', 'AdahAbernathy5@nowhere.com', 'Hà Giang', '0981120042', 'R1', 'Nữ', 'R559', '1970-01-01 02:20:49', '1987-09-17 00:46:58'),
('34cde64f-62e4-186c-77dd-867949feb8b5', 'Ngô Thanh Toàn', '9Ty+8Qldr3jhHryjP2/f0w==', 'LaveraLRoberge63@nowhere.com', 'Quảng Ninh', '0986304715', 'R3', 'Nam', 'U0Y3', '2009-08-11 03:49:55', '1970-01-01 00:16:31'),
('3590dd80-43d2-1325-8732-6a1673ffca7c', 'Bùi Hoàng Việt', 'ZF1yViOcpRV3oxN2r84Hvw==', 'AbbyRBlalock826@example.com', 'Ninh Bình', '0982390173', 'R3', 'Nữ', 'XR36IU10D9', '2002-04-22 13:45:35', '1970-01-01 00:00:07'),
('3599ef50-13ed-5404-0e63-eeb1d8ed8cef', 'Bùi Thiện Tính', 'YFVWuuHjIZ0te/B+/LAsUw==', 'OlgaFerry@example.com', 'Thái Bình', '0989270076', 'R2', 'Nam', '37NG8KK', '2018-02-14 09:06:24', '1976-06-05 12:26:57'),
('3721d21d-5c1d-1e10-1563-eeb1d8ed8cef', 'Phạm Tịnh Nhi', 'VdsRU0O8JLSpbwwVRxSG7A==', 'Ackerman9@nowhere.com', 'Quảng Ninh', '0989580768', 'R2', 'Nữ', '9G6L9Z3N1QP45', '2019-04-07 01:50:08', '2010-08-23 19:44:09'),
('37cf0ec7-4909-5dc9-a37d-e8c757976496', 'Nguyễn Trúc Phương', 'i0Pg5skKOKcdz9bjHxHDEg==', 'Funk969@example.com', 'Hà Giang', '0983376927', 'R1', 'Nam', '9B5WNIA42KTGSU9XZ43609D2CJ52U21CA0KZ7069364VTNCFX', '1993-12-20 00:50:14', '1979-09-22 01:53:23'),
('380799e8-2bfa-4f0f-8e32-6a1673ffca7c', 'Đặng Diễm Quyên', 'XNqRcpxZu0yy2pbgvxXW4g==', 'BatisteK714@example.com', NULL, NULL, 'R3', NULL, NULL, NULL, NULL),
('3856e8f7-535c-632a-83dd-867949feb8b5', 'Nguyễn Giang Nam', 'o1RjzCjQDEdICKm8kZb+WQ==', 'RhondaBreedlove76@example.com', 'Hải Dương', '0980195638', 'R1', 'Nữ', '8IEHCEDDSS48CN33UU96JHH5', '1970-01-01 00:08:43', '1970-01-01 00:07:04'),
('38b1d642-47b7-7c97-6692-08c864661f9c', 'Võ Yến Nhi', 'TY/klHsmd6WoUbwIbIM3/Q==', 'SaundraCavazos@example.com', 'Hà Nội', '0982029841', 'R2', 'Nữ', 'E9UV4S3WRIZIPV3D7JP3149O1FH', '1991-03-26 19:42:35', NULL),
('392fb6ca-399e-2320-7192-08c864661f9c', 'Hồ Hữu Thống', 'iMbzO6/gaqvE9Spsbw9bgA==', 'ggcaizj841@example.com', NULL, NULL, 'R2', NULL, NULL, NULL, '1987-11-04 23:08:40'),
('3965bd1a-2544-467d-80dd-867949feb8b5', 'Bùi Bảo Chấn', 'y5xyFCa3Nt5f+iP8ejZ7JA==', 'Hutchison65@example.com', 'Ninh Bình', '0985027496', 'R3', 'Nữ', '44MK2993QFUO7O4FRVI33', '2004-04-27 22:36:48', '1970-01-01 00:01:09'),
('3ab17eb8-4928-4275-8332-6a1673ffca7c', 'Võ An Ninh', 'X83TjoAO7vvzfpyuTD6+Ew==', 'MaynardGivens@example.com', 'Hà Giang', '0986576541', 'R2', 'Nữ', '0B98O5', '2002-03-17 04:04:19', '2014-08-18 00:43:24'),
('3abc4ce5-462f-5db9-9e7d-e8c757976496', 'Trần Gia Phong', 'LJqmbcLV5qfEeK+T3WTpuw==', 'Melendez@example.com', 'Thái Bình', '0984021422', 'R3', 'Nữ', 'J1DJ082J', '1970-01-01 00:00:36', NULL),
('3b4d46a3-7a40-30a2-fe17-7000f455f3d5', 'Phạm Xuân Vũ', 'A5GT6YuoXgvuTPeqcKALnw==', 'Grimes665@example.com', 'Hà Giang', '0987669291', 'R2', 'Nam', '25AQ0E', '1970-01-01 02:09:58', '1970-01-16 02:19:39'),
('3b58cf74-16ac-69f6-aa7d-e8c757976496', 'Bùi Mạnh Thiện', '1/3amEswmU6UaiC2nesx7A==', 'Babb@example.com', 'Hà Giang', '0984734044', 'R2', 'Nữ', '39R4M39NWK6F8HB4LAK914Y1V4W66W08690Y2DK355FL2M379H9F15M494DJUJ38SY08', '1970-01-01 00:01:29', '1970-01-01 00:06:32'),
('3c19bf05-3077-4b76-27cb-66948daf6128', 'Võ Hiểu Lam', 'wUYUcdhkeCoajceYrr+S6Q==', 'Agnew@example.com', 'Hà Giang', '0985368674', 'R1', 'Nữ', 'T5GC5539U27C9PW', '1997-01-16 11:39:20', '2008-07-28 18:50:29'),
('3ce59559-28e3-40e4-1463-eeb1d8ed8cef', 'Bùi Danh Thành', 'PnCO9cKL2r11Z9peorJtHg==', 'Dale279@example.com', 'Hà Nội', '0980920188', 'R1', 'Nữ', '3L88X96R0526LYR375H49C28R1F9585X0G3AF9Z5B8GGE555', '2014-12-26 15:49:08', '1973-12-17 22:28:16'),
('3d780ac8-3fb5-5c89-8932-6a1673ffca7c', 'Ngô Thanh Hoa', 'jgaaKECWouEJ8+5eQAdrfQ==', 'Collier@example.com', NULL, NULL, 'R1', NULL, NULL, NULL, NULL),
('3ef08d53-5bf3-1e97-9790-67245e8b283e', 'Hồ Quang Lân', 'PZ/6oZppc2V6wD/iMaw3xg==', 'ConcettaEnnis544@example.com', 'Quảng Ninh', '0987433364', 'R2', 'Nữ', '6359H053TIF7RV6Y651F68O7XGYH76L2E047G4R8CSX41B74268J21AH4J8WSH', '1971-07-20 05:19:31', NULL),
('3f66f2d6-688b-4161-5f92-08c864661f9c', 'Đặng Công Hào', 'rHfFFQbgGFK6e08A9x0rvA==', 'LucillaAbreu267@example.com', 'Quảng Ninh', '0984432810', 'R3', 'Nam', '417YNW0V52D7S186131E', '2011-07-11 23:36:01', '2013-01-02 08:01:36'),
('3f851737-2976-4bc0-22cb-66948daf6128', 'Phan Xuân Dung', 's5mT1/qK59QNIp1rzCF9dw==', 'AlejandraNorris@example.com', 'Quảng Ninh', '0989014848', 'R3', 'Nam', 'SR395A50Y', '1998-07-08 01:44:32', '1995-06-07 22:38:09'),
('3fcda397-772d-53a4-25cb-66948daf6128', 'Lê Thúy Hương', 'U+3VJkJ0HCdVYk/6ODf3qw==', 'DanteSchott9@example.com', 'Bình Dương', '0989994318', 'R3', 'Nữ', '5728P68D0YP328974DELAU6TM8BVSP8V8', '1970-01-01 00:00:01', '1992-07-16 16:16:56'),
('40036f5e-657f-2c3d-9f7d-e8c757976496', 'Võ An Nam', 'zK4el3WBlqRM1VYFytm2Ww==', 'Rosalee_RMatney542@example.com', NULL, NULL, 'R3', NULL, NULL, NULL, '1970-01-01 00:00:39'),
('404fe340-1fd3-414b-aadb-e5d54223c257', 'Trần Lương Tài', '70r6j5L9INlAKghckiTLaA==', 'AmosBliss189@example.com', 'Quảng Ninh', '0988184404', 'R2', 'Nữ', 'WU', '1970-01-01 00:01:23', '1970-01-01 00:57:34'),
('4103f42d-1ebd-52dd-0f80-e8e2a817c80e', 'Phạm Xuân Quân', 'rnV779QBMYsWxPQpAgL23g==', 'JoanieB.Hoover@example.com', 'Hà Giang', '0981009030', 'R2', 'Nam', '5FJR9DJ4YV9J4', '2018-07-15 15:05:28', '1980-05-11 05:19:41'),
('4188bc78-6e7e-2c0a-7fdd-867949feb8b5', 'Trần Hiệp Hào', 'k/GLMIZ1yS9rWr8/GP0zRw==', 'HaywoodBroome@example.com', 'Hà Nội', '0984934161', 'R2', 'Nam', '44CM4AM962O3101864S734L3XGJ6XFU', '1970-01-01 00:16:13', '2011-11-26 04:25:50'),
('4213347c-7d41-76e6-9d90-67245e8b283e', 'Nguyễn Thái Ðức', 'hUuFy/8nUvy4hga8p2+Dxg==', 'Afton.Collado715@nowhere.com', 'Hải Dương', '0989725044', 'R2', 'Nữ', 'L5C6154RPJ69223U0P3RN0', '2003-02-03 11:56:59', '1970-01-01 00:00:03'),
('4296b118-76aa-3241-7edd-867949feb8b5', 'Nguyễn Tố Uyên', 'KCou1wrwg/ZTqvv89YF0HQ==', 'LyndsayColley@nowhere.com', 'Hà Nội', '0988180612', 'R1', 'Nam', 'ZUPH013M33036RH884J3425172ZL42H63', '1970-01-01 00:00:02', '2018-03-17 07:49:31'),
('438fec4c-2dad-30d7-a07d-e8c757976496', 'Dương Bình Ðạt', '1bsae2YCbr5lRT7eVCcRnA==', 'Adan_Busch@nowhere.com', 'Hải Dương', '0982062948', 'R1', 'Nữ', '5O6OTKLP3607IVF46Y1O1ZF8I7CL2447W9TCPGGLJN5UWU8F1XOUW456O2628Z4P03EK70M525368BZH02SG53SE28Y0H', '2018-04-02 03:02:12', NULL),
('439cdac8-4380-1e2d-0f63-eeb1d8ed8cef', 'Nguyễn Nam Phi', '8k+yuPcohUHAFA/H/rp9uQ==', 'Beeler85@example.com', NULL, NULL, 'R1', NULL, NULL, NULL, '1970-01-01 00:07:20'),
('4448a185-202a-56da-8632-6a1673ffca7c', 'Bùi Hải Thanh', 'BwoEXR9G7o9/IJK4QMpH4Q==', 'PughC@example.com', 'Bình Dương', '0980528488', 'R3', 'Nam', '64G94989TQ09H51', '1978-12-08 18:53:48', '1970-01-01 00:01:23'),
('45536100-7fba-5a99-24cb-66948daf6128', 'Bùi Huệ Hồng', 'xvw7EQkeLVaYG3eMSyt6jg==', 'Barnhill9@example.com', 'Quảng Ninh', '0981058211', 'R3', 'Nữ', 'WX1VPWRTR5Q7304919L2M3V475C94WZJ6280TU5N', '2022-05-01 00:47:20', '2006-11-04 12:27:56'),
('4577565a-7e3e-493a-74dd-867949feb8b5', 'Ngô Sao Băng', 'lhAfJTlHur+CDye0jrsjRw==', 'Monroe.Rinehart@nowhere.com', 'Hà Nội', '0986176320', 'R2', 'Nam', 'E9DL2Q507C02627871M5U1', '1990-09-22 03:29:20', '1990-03-25 12:03:29'),
('469b3ece-744a-45d5-957d-e8c757976496', 'Nguyễn Phi Nhạn', 'NQORmuq2s5RRJgNN2sO8Ww==', 'Morehead@example.com', 'Bình Dương', '0985426756', 'R1', 'Nam', 'T3NO40JEX3LQ8SI15W4575', '2005-11-04 22:06:31', '1984-09-13 21:09:47'),
('46f514e3-3598-177c-6192-08c864661f9c', 'Lê Hoài An', 'kogU6gTBPj9HJkpMdCKrUQ==', 'utxpbh4739@example.com', 'Bình Dương', '0989736333', 'R1', 'Nam', '3Q', '2001-10-25 14:34:14', NULL),
('4729a19e-5a81-6e74-6a92-08c864661f9c', 'Đặng Mai Thy', 'TaSsEMKIfd0V91f23jipCg==', 'Barbour@example.com', 'Ninh Bình', '0984105611', 'R3', 'Nam', '8V33X', '2010-10-21 06:57:39', '1984-02-15 03:08:16'),
('47405a55-5845-562c-7ddd-867949feb8b5', 'Huỳnh Việt Thắng', 'xKYS0Po02SDCTsg/rU8UYQ==', 'HomerCalvin@example.com', 'Bình Dương', '0986452702', 'R3', 'Nam', '96', '1970-01-01 00:01:15', NULL),
('4760d71f-6e2f-5b32-19cb-66948daf6128', 'Ngô Ân Thiện', 'Kq96WBa1XDnq5vYSckatmA==', 'uadm55@example.com', 'Hải Dương', '0980508013', 'R1', 'Nam', '0E85J6W', '2021-05-05 19:38:43', '1987-05-08 18:24:04'),
('47f60f67-6087-2a86-abdb-e5d54223c257', 'Bùi Quang Ðạt', 'iS6vp/HNxnlUboLYsp8TYQ==', 'pcvmbj959@nowhere.com', 'Quảng Ninh', '0982482481', 'R2', 'Nam', 'PNX3LE42K573AD99653G5WLZ3T58W9P34', '1970-01-01 01:00:18', '1975-12-28 20:29:57'),
('48adb0bd-7040-1241-6e92-08c864661f9c', 'Đặng Phục Lễ', 'tn+ZDc+z0Bz0fPE7qCwLkQ==', 'RamonSierra4@nowhere.com', 'Hà Nội', '0985974114', 'R1', 'Nam', '4L2RU3E43J', '1985-10-01 18:12:25', '1998-07-11 02:34:38'),
('48c40821-1c72-189a-6792-08c864661f9c', 'Hồ Nhật Tiến', 'pHY0CnzxC7TPcnqitFj1aQ==', 'Gaylord_Schwarz28@example.com', 'Ninh Bình', '0982915978', 'R2', 'Nam', '5SOGL8LGF72VW5AI4K7KG7X517E8TX144', '1986-05-08 20:43:18', '1970-01-01 01:41:19'),
('4943c139-6a49-4d6e-1663-eeb1d8ed8cef', 'Trần Hạnh Phương', 'QTOoeC/UJgrpC3JvmtH96w==', 'Saenz@example.com', 'Hà Giang', '0982696402', 'R1', 'Nam', '1G41Z06', '1970-01-01 00:01:35', '1971-09-25 02:13:13'),
('4b5f36b2-71d7-58eb-badb-e5d54223c257', 'Bùi Phương Trạch', 'WORz8l3JsSrPmI94vCG5uw==', 'Devorah.Acevedo@example.com', 'Hà Giang', '0988499384', 'R1', 'Nam', '7R02', '1970-01-01 00:04:21', '1970-01-01 00:07:53'),
('4c2386b1-57fb-15fa-1063-eeb1d8ed8cef', 'Ngô Hải Hà', 't1MeWmJIOHBA6R53jGYfwQ==', 'Cohen311@example.com', NULL, NULL, 'R1', NULL, NULL, NULL, '1975-03-26 05:22:36'),
('4cd4bba1-49ac-6e4c-b4db-e5d54223c257', 'Lê Thiện Tính', 'oPAF8c5ejqdd7OaqWo82/A==', 'hcjafl3608@example.com', 'Thái Bình', '0988706990', 'R1', 'Nam', '2TVHYYA7AA9TFMZTU3PF6BSR0CY', '1970-01-01 00:11:09', '1970-01-01 00:00:09'),
('4d79d901-1edc-5c5b-0780-e8e2a817c80e', 'Huỳnh Minh Khang', '9m+MtTYoJX2vO8cAmBWoDw==', 'Dalila_JRust@example.com', 'Hải Dương', '0984676746', 'R1', 'Nữ', 'FK63TGUUIW86CQU339I8O367MZ9Z824GZWWD5VLP4536I11', '1970-01-01 00:06:40', '1970-01-01 00:00:04'),
('4d7b21db-2e02-12b7-a9db-e5d54223c257', 'Vũ An Khang', 'MFb0nzFEqL2uhnxp2Uug9Q==', 'gxsgr25@example.com', 'Hải Dương', '0985202630', 'R1', 'Nữ', 'I8671X6P839X', '1970-01-01 00:15:42', '1980-12-04 00:46:15'),
('4e01ca19-178d-1579-9c90-67245e8b283e', 'Võ Hoàng Duệ', 'v0QLo4d+f1X4EgtfG5Otdw==', 'Francesco.Walter@nowhere.com', 'Hà Nội', '0983558383', 'R1', 'Nam', 'GQ14H10J7K7R5AGS5INW4OK506EB1CA03Z4C00', '2012-11-03 23:30:04', '1996-05-15 20:52:43'),
('4e272fc4-7875-78d6-7d32-6a1673ffca7c', 'Vũ Quang Sáng', 'nIQ9BemXcOfsuE31juBnwQ==', 'qpzre411@example.com', 'Hà Giang', '0984830435', 'R2', 'Nữ', 'I52', '1995-07-15 15:57:28', '1970-01-01 00:00:08'),
('4eceddac-7dc2-38ea-7bdd-867949feb8b5', 'Hồ Linh Duyên', 'Oc5WXv+3zFieKiZrqkyAGA==', 'AngelitaX.Sandoval@example.com', NULL, NULL, 'R1', NULL, NULL, NULL, '1991-04-28 20:49:45'),
('4f6d1696-757a-42a0-0a80-e8e2a817c80e', 'Đặng Ánh Hoa', 'r5+6ZPJQpn0gu1we9vO4Cg==', 'NorineBuckingham@example.com', 'Quảng Ninh', '0987092664', 'R3', 'Nữ', '32', '1970-01-01 00:01:21', '1996-03-16 08:38:51'),
('50d65da3-631c-5139-9b90-67245e8b283e', 'Hồ Hồng Nga', 'jKEZKU9DNVkuGwVq3DApbw==', 'Ada.JCrosby@nowhere.com', 'Hải Dương', '0985989168', 'R2', 'Nữ', '760769S89MY69R08MK5UBYL147C5N36M43175J78MCGA89WI4GAPPNYBF7M73CE', '1984-05-27 09:44:07', '1970-01-01 00:41:56'),
('511f2482-76be-16cb-84dd-867949feb8b5', 'Vũ An Khang', 'N0ChN7ueRmqv8GPiwpFcKw==', 'Melton@nowhere.com', 'Hà Nội', '0986944623', 'R3', 'Nữ', 'DZ903JK1', '2018-01-22 10:16:00', '2004-11-18 16:19:02'),
('52f674bb-7249-7b72-8b32-6a1673ffca7c', 'Nguyễn gọc Linh', 'ScZNEdduuhrh98vyzBaZ9w==', 'kxlfgxb3@nowhere.com', 'Hải Dương', '0986202133', 'R1', 'Nữ', '8WQNJ2', '1999-07-30 17:31:04', '2008-12-26 14:46:25'),
('52f7159d-5242-1af8-9c7d-e8c757976496', 'Nguyễn Tường Lĩnh', '1bsae2YCbr5lRT7eVCcRnA==', 'Kinney@example.com', 'Hải Dương', '0983586309', 'R2', 'Nam', '38M', '1976-07-05 04:00:15', '2021-08-22 11:12:56'),
('53f6b59c-6af6-4204-6292-08c864661f9c', 'Phan Phước Nhân', 'nXNnHo2Qz9XS8lrxC3sj9g==', 'Edwardo_P.Mcclintock965@nowhere.com', 'Ninh Bình', '0989566910', 'R2', 'Nữ', 'JT2', '1979-03-05 18:11:50', '1970-01-01 00:00:06'),
('550c9284-29ba-7fb5-7392-08c864661f9c', 'Đặng Hồ Nam', 'ac9ZbdAA6Jk4bPBUVw2X8w==', 'ysitzv30@nowhere.com', NULL, NULL, 'R1', NULL, NULL, NULL, '2007-01-15 20:05:43'),
('5608f456-3b97-2e05-5d92-08c864661f9c', 'Vũ Tuyết Trầm', '1kOwmq+6of12T1MG7flbzg==', 'Hoover@example.com', 'Bình Dương', '0981782473', 'R1', 'Nữ', 'US4', '1971-12-29 12:34:14', '1973-12-04 15:40:34'),
('561eb2f7-48b8-58dd-6892-08c864661f9c', 'Dương Thu Sinh', '8itqX2VCFJQvAa2aYMabOw==', 'ogpwir97@example.com', 'Thái Bình', '0980782426', 'R1', 'Nam', 'D6I5US6X63586Y09W02LON4PI6T9JZL6KGI9J8P93914VS493G159RAO697MRU6P1567CU372', '2012-09-06 23:22:33', '1970-01-01 00:01:17'),
('5660d465-6020-48f3-75dd-867949feb8b5', 'Huỳnh Tùng Lâm', 'bg37j/3rQAdQLjYC4AXD7g==', 'phkfhcmu_jjjdjuvrms@example.com', 'Thái Bình', '0984473122', 'R1', 'Nữ', '49EH211YJL4H341LZ40TC5C7PG5N4Y16H', '2008-09-02 04:01:40', '1970-01-01 00:06:55'),
('56957607-562f-5d6d-1ecb-66948daf6128', 'Vũ Yến Phượng', 'OyglwkCx2Px4cybRX5+yQg==', 'CleoAbraham329@example.com', 'Hà Giang', '0980350588', 'R1', 'Nữ', '802MSTXC', '1970-01-01 01:15:49', '1970-01-01 00:09:11'),
('56978ca4-3960-6c89-1963-eeb1d8ed8cef', 'Đặng Thái Ðức', 'I8Iir+9OFy6JzO7ScAt6mg==', 'gdlzrixn_lzief@example.com', 'Hải Dương', '0981126175', 'R3', 'Nam', '0CUX9SD', '1999-06-22 07:51:14', '1970-01-01 00:00:03'),
('56b19619-3b4b-5ed3-6d92-08c864661f9c', 'Đặng Cao Nguyên', 'OZl5/72ue0YPpQ76S6a1Rg==', 'Acker@nowhere.com', 'Quảng Ninh', '0980585121', 'R2', 'Nam', 'Q94FOIR74G', '1970-01-01 00:14:32', '2007-03-08 17:46:48'),
('56ea0e4e-18dc-1b50-6f92-08c864661f9c', 'Đặng Hồng Liêm', 'StIVasJyZMv3sHNr+Sq/4Q==', 'LeviZ_Gossett@example.com', NULL, NULL, 'R2', NULL, NULL, NULL, '2022-11-17 18:49:42'),
('578a959e-1fe6-650e-b8db-e5d54223c257', 'Nguyễn Diệu Thiện', 'VrBoEgn7PIckcnTTGMkw/w==', 'LynnDowling@example.com', 'Ninh Bình', '0983583214', 'R1', 'Nam', 'W3F3HYV3', '1970-01-01 01:53:40', '1990-10-18 15:44:18'),
('58d8d8a7-140b-5c87-82dd-867949feb8b5', 'Phan Thư Lâm', 'YUBtONTTYU/pcCh6R30uuA==', 'James4@example.com', 'Thái Bình', '0983116206', 'R2', 'Nữ', 'A715', '1970-10-02 15:17:20', '1970-01-01 00:00:22'),
('59d19422-6657-452e-a7db-e5d54223c257', 'Nguyễn Công Bằng', 'TSN+B5tpyTahooDqgXYq1Q==', 'FelipaAbernathy@nowhere.com', NULL, NULL, 'R2', NULL, NULL, NULL, '1999-09-25 13:30:10'),
('5abcb7aa-4be0-373c-b7db-e5d54223c257', 'Lê Bích Quyên', '6wxTvHkPi/3Z2NxgnL+f4g==', 'Ramsey5@example.com', NULL, NULL, 'R1', NULL, NULL, NULL, '1970-01-01 00:06:18'),
('5ae2d70b-201d-3e23-7f32-6a1673ffca7c', 'Đặng Quỳnh Tiên', 'XQUtyOEsp/n5fbBf9coPkg==', 'sdyfq9887@nowhere.com', 'Ninh Bình', '0982957938', 'R3', 'Nữ', 'SYAN31Y62537MI7W', '2005-01-13 19:46:54', '2002-05-10 14:02:59'),
('5b2fcdf5-2050-7cb2-8f90-67245e8b283e', 'Võ Lam Giang', 'zRB12Eil4BQr07XWZyYEHA==', 'Caldwell@example.com', 'Thái Bình', '0988057234', 'R2', 'Nữ', '5W4C84E6KH', '1984-10-15 08:04:20', '1970-01-01 00:10:39'),
('5b50bf11-3f80-3d31-9032-6a1673ffca7c', 'Huỳnh Xuân Phượng', 'Pkdbqv9Km+pwOHunq4h5rA==', 'Addie.Sanderson3@nowhere.com', 'Quảng Ninh', '0980123563', 'R2', 'Nam', 'AB3400OST41D99EN4Q22K08S116RP22BRY6V64CX033QMK5G88HX93E6FF1H31W0G3WN5D5LU089M7YJK743Y', '2002-12-02 15:44:03', '1970-01-01 00:00:46'),
('5badffd8-18c8-3f76-6492-08c864661f9c', 'Dương Thế Duyệt', 'zqeEOWgRcj96TAoc2F9ZMA==', 'Card@example.com', 'Hà Giang', '0987443210', 'R1', 'Nam', 'P427OP4', '2021-01-10 14:54:50', '1970-01-01 00:10:14'),
('5c63ba8f-59bb-6d2f-9990-67245e8b283e', 'Ngô Trúc Linh', 'sRT5YtpYnpND5wiKfUbT+A==', 'KarlynBurt479@nowhere.com', 'Bình Dương', '0985984149', 'R2', 'Nam', 'F', '1978-02-14 03:07:20', '1998-05-12 00:36:43'),
('5c86869a-6d0c-7cb1-2dcb-66948daf6128', 'Huỳnh Quang Tài', 'i0Pg5skKOKcdz9bjHxHDEg==', 'Jannet.Gorham8@example.com', NULL, NULL, 'R2', NULL, NULL, NULL, '1970-01-01 00:01:13'),
('5d69f482-4df8-2e61-0e80-e8e2a817c80e', 'Lê An Khang', 'o5/Nog3osHXA3XHpakE5xA==', 'Pulley@example.com', 'Hải Dương', '0989585557', 'R1', 'Nam', '59RFQB3', '1982-12-14 00:30:30', '1970-01-01 00:01:40'),
('5fbbda7e-7566-416f-9b7d-e8c757976496', 'Phan Ðình Phúc', 'eyqyJCxUyLjDufqcioglGA==', 'AddieD.Armstead@example.com', 'Thái Bình', '0989286428', 'R3', 'Nữ', '55RSXTQ5N4CV0', '1970-09-05 11:59:28', '1970-01-01 00:00:04'),
('60084fec-3509-2779-8432-6a1673ffca7c', 'Phạm Bảo Bảo', 'x+/+hoss2GLZR5T0ZVVlxw==', 'ymqukl565@example.com', 'Ninh Bình', '0982164021', 'R1', 'Nữ', '9XJ8TZX9M4O81WIFY99PF49TR', '2010-05-20 06:32:20', '1970-01-01 00:00:07'),
('6081dc00-4df0-5184-9690-67245e8b283e', 'Lê Uyên Vi', 'wg+rLfWBQWpcR2dK6a7AnQ==', 'Abram.Burdette919@nowhere.com', 'Thái Bình', '0980795135', 'R2', 'Nữ', 'S1Z0PEB8U2613S2J9Q0B2SK', '1997-05-15 21:41:08', NULL),
('6149c4f4-425b-60e0-b3db-e5d54223c257', 'Trần Ân Thiện', 'IwlJ1xmvy5C7T6orijpqvA==', 'Annis.Blaine@nowhere.com', 'Thái Bình', '0982429170', 'R3', 'Nữ', '397BLPF0H', '2011-09-06 09:02:33', '2011-03-25 01:22:57'),
('61a45b9e-55c1-3dbb-f917-7000f455f3d5', 'Nguyễn Tuyết Mai', '5ond6BFqdbhyrEyPeXIRKA==', 'Rudolph358@example.com', 'Hà Nội', '0984058042', 'R1', 'Nữ', '54Q25CW0SLCCQC0HRL1714T2MIL722I50484GHYA1ECB5F5A2SR5YRZE35C9VPX59D2CFTKM', '1988-12-04 19:25:43', NULL),
('61a68ac1-3e74-5149-a290-67245e8b283e', 'Phan Huy Quang', 'rJPKr+/7LVuBU3bjWzGIeg==', 'JonahCleveland21@example.com', 'Bình Dương', '0984436973', 'R2', 'Nữ', '8KX6XS456P38H948D079E', '2003-05-13 21:08:27', '1970-01-01 00:00:03'),
('61de96a0-125e-6f06-9e90-67245e8b283e', 'Huỳnh Hồng Giang', 'VdLPQM7ktFSwqaa7s1fbVg==', 'Leif.Ainsworth4@example.com', 'Hà Nội', '0989186203', 'R1', 'Nữ', 'LOXOE65282H4Z721075VM7W8155W11', '1988-07-27 13:58:08', '1978-07-05 21:41:27'),
('62071e5d-7876-6982-a67d-e8c757976496', 'Phan Bình An', 'XAqpPuG+S7duFEiJYMFF7A==', 'dwwzqatq8@example.com', 'Thái Bình', '0989960484', 'R1', 'Nữ', 'HE91Y8V82TCQ2D70', '2020-07-14 05:37:07', '1970-01-01 00:01:32'),
('620dbda4-3d7b-6ef2-89dd-867949feb8b5', 'Vũ An Khang', 'ZuW62RDS6mEWJZabe25Z1Q==', 'fcikhuhp_fundw@nowhere.com', 'Bình Dương', '0987325441', 'R1', 'Nam', '2QR03I', '1970-01-01 00:00:55', '2011-10-31 13:08:30'),
('6429b0f4-1391-7f32-9390-67245e8b283e', 'Trần Hữu Phước', '0ShxP5/7Uk/eHg8msDs+iw==', 'Ketchum@example.com', 'Hà Nội', '0988019043', 'R2', 'Nam', '5', '1975-08-29 03:27:58', '1983-11-11 00:37:59'),
('645f2e5c-7670-66a0-6092-08c864661f9c', 'Huỳnh Quỳnh Sa', 'juZKMjcci95WNwBFE6lBfA==', 'Nickie_B_Ambrose@nowhere.com', 'Bình Dương', '0981795541', 'R1', 'Nam', 'LH8A4NPRE1UI452ND875OJHB69A88HR3JG09I42ZUW8L', '1975-10-06 15:37:42', '1970-01-01 00:00:38'),
('65a8faaa-15cf-61dc-7092-08c864661f9c', 'Vũ Linh Châu', 'isS9GXIQQI8nLUdr3v740w==', 'Anthony@example.com', 'Hà Giang', '0983466537', 'R3', 'Nữ', 'YL3J0FCG50HAW1NM5F749A5N', '1970-01-01 00:02:39', '2020-03-19 08:33:43'),
('66e9a5b8-2a02-52f5-85dd-867949feb8b5', 'Huỳnh Quang Dương', '7WP8EG3GnuHb4yv1WZiy0A==', 'Schaeffer62@nowhere.com', 'Hải Dương', '0980554925', 'R2', 'Nam', 'P7LS67O20794AFI', '2017-10-07 15:01:23', '1998-04-19 07:04:09'),
('6719e18d-6121-4bee-8c32-6a1673ffca7c', 'Đặng Bá Thành', 'aOryh/9f7YkGnP5I2ZGM+Q==', 'Alicea353@example.com', 'Bình Dương', '0989600818', 'R2', 'Nam', 'NV09YIJUUUHM506G38TVF597Z74ZFO90LV8593QM', '2015-07-18 01:56:35', '1970-01-01 00:07:18'),
('6764ab86-6fcc-2757-8032-6a1673ffca7c', 'Phạm Phương Ngọc', 'DjEHySF//hwwX9XfqpQlgw==', 'Russell@nowhere.com', 'Bình Dương', '0984064317', 'R2', 'Nữ', '367J68H58J9493Q4OW5W9H7W01EWCTQ3Q06829O6NJJ937LQX4M9S3W5ML6QB4922R6EGRC1J5TUCI1D', '1970-01-01 00:05:13', '1970-01-01 00:00:10'),
('67b5c284-1c59-4a0a-0580-e8e2a817c80e', 'Trần Tâm Thiện', 'KLyfY1JEgUGvaEyEv1LzdA==', 'kybxospa.lacod@example.com', 'Ninh Bình', '0988166208', 'R2', 'Nam', '3S6JB0Q8', '2015-04-24 01:44:20', '2007-03-17 17:16:11'),
('67ef417b-756d-6f15-a27d-e8c757976496', 'Bùi Mạnh Cương', 'O+6ShSAC/dewBsX9yd2Pig==', 'hkskovwj8764@example.com', 'Bình Dương', '0987542177', 'R3', 'Nữ', 'S7B345T3', '2000-12-13 10:23:41', '2006-03-27 10:29:51'),
('68478414-705a-2626-5c92-08c864661f9c', 'Ngô Mỹ Phương', 'pGw7VPLJhxzYHa96kySZwA==', 'Valdez@example.com', 'Hà Nội', '0980818164', 'R1', 'Nam', 'K261F7Q918750Q49SXI353FTIF7UNCF2699889L207Y4F2D3O6EMT4PK3WWC2IIR6GO1ZB54SAW41', '2012-06-08 00:18:55', '1973-07-02 04:28:38'),
('6916f8cf-1279-16d8-9290-67245e8b283e', 'Đặng Quốc Vinh', 'wUPQvEZdNUW9FpAXFcYcxA==', 'pqfmmt48@example.com', 'Hà Nội', '0989650977', 'R3', 'Nam', '9DQSDML1X2QY', '2005-02-15 12:19:46', '1971-06-11 19:13:22'),
('696f0f83-27ea-5246-1380-e8e2a817c80e', 'Nguyễn Duy Mạnh', 'pGw7VPLJhxzYHa96kySZwA==', 'ferjfcg7@nowhere.com', 'Hà Nội', '0988362258', 'R3', 'Nam', 'ZV304N18B586L4602I99190AL', '2009-01-27 02:25:24', '1995-10-26 17:50:10'),
('698623e9-1def-6cb3-fa17-7000f455f3d5', 'Dương An Nhiên', 'o+crOCQKEfuss71+MIlxRA==', 'Ackerman@example.com', 'Ninh Bình', '0980253442', 'R1', 'Nữ', '55M90860577WN9U0W21654WIW11VSSC5B29TPXL0', '1970-01-01 00:09:14', NULL),
('69cdb3c5-55bc-2a7a-9a7d-e8c757976496', 'Nguyễn Bình Thuận', 'nRofmkf8BKxT2nCjG4lXrg==', 'MalcomKnutson757@nowhere.com', 'Bình Dương', '0985872558', 'R1', 'Nam', '064RN1XSUXFPFOWZHEQ0IO9T', '2002-03-31 16:11:36', '1970-01-01 01:59:55'),
('6a4d99cd-242a-6200-7add-867949feb8b5', 'Đặng Bích Hải', 'NiMAhfSGGCn5IftqCAXc/Q==', 'BalderasG5@example.com', 'Hải Dương', '0987888427', 'R1', 'Nam', '0561B982TEVCKDC8', '1970-01-01 00:02:22', '2001-07-06 13:38:22'),
('6a779fff-7bc4-54f4-b5db-e5d54223c257', 'Nguyễn Cao Nguyên', '/JHypzqkwv3ihH+i7FwJJw==', 'eurkdbiu_qojufc@example.com', 'Hà Nội', '0987704177', 'R2', 'Nam', '1A76BSA8E2W6SDIMAMB293T61VORV04RMN0G3R9RAO', '2013-02-02 19:42:05', '1973-10-12 04:46:21'),
('6af6ef19-44ef-22a6-0118-7000f455f3d5', 'Nguyễn hánh Hà', 'KVLuUELIxSPeokf+Sa26XA==', 'AlfordM9@example.com', 'Hà Nội', '0988020095', 'R3', 'Nam', 'G555WC9J', '2019-05-09 16:35:42', '1970-01-01 00:01:27'),
('6c97b353-5d7d-4095-1dcb-66948daf6128', 'Hồ Hảo Nhi', 'NY4nX4LexmgOvkmwBZhklg==', 'Keene136@example.com', 'Thái Bình', '0988993687', 'R1', 'Nam', 'NWFO98W4QVYG86DW96L', '2010-07-20 04:35:55', '1970-01-01 00:00:08'),
('6de8272b-7b3b-319f-8a32-6a1673ffca7c', 'Dương Viễn Cảnh', '6gHoBTV/hNMx1cjFjEOxLg==', 'Lyda.Kraft297@example.com', 'Bình Dương', '0985798261', 'R3', 'Nam', 'TGPI55RP29546541B5Y311CVWPV6', '2015-03-07 04:58:29', '1970-01-01 00:00:23'),
('6f2475a8-1ff5-13e7-0680-e8e2a817c80e', 'Dương Bảo Sơn', 'M1HknwbW/BLNI5+25V3yGg==', 'Larson115@example.com', 'Ninh Bình', '0984495767', 'R2', 'Nữ', 'YOAB2Y4B911ZL5L', '1974-07-18 11:15:02', '1970-01-01 00:00:02'),
('6f9b639b-6124-3874-a87d-e8c757976496', 'Trần Thế Hùng', '+Gj6Zu8fnBxNY342ew7qbQ==', 'Olds@nowhere.com', 'Hà Giang', '0985782647', 'R3', 'Nam', '359B1EUNE0', '1983-05-05 18:09:59', '1970-01-01 00:01:04'),
('70253ec7-2e38-67a9-b1db-e5d54223c257', 'Phan Việt Thông', 'ZKe0SztOMfG4zSOVkLy88g==', 'MatthewHindman@example.com', 'Hải Dương', '0987916885', 'R2', 'Nữ', 'SPUM5O', '2020-12-23 12:03:14', '1970-01-01 00:09:31'),
('7050d79b-6948-3c66-1fcb-66948daf6128', 'Dương Gia Bạch', 'q5uha4NgzE8VB53LHwiHiQ==', 'ConnieAllard@example.com', 'Hải Dương', '0988781646', 'R3', 'Nam', '00BSSXJ8906IXC', '1970-01-01 00:09:39', NULL),
('70af83de-413e-63ef-6592-08c864661f9c', 'Ngô Tuyết Hoa', 'hvgaBKjYHXZQAal20C/F7w==', 'Dewayne_Wheaton@example.com', 'Bình Dương', '0980718616', 'R3', 'Nam', 'P833Z2N4A0XM7GRK5A8P6W903LP1MY6D1177B7V8Z', '1975-11-27 00:53:59', '2008-05-31 06:40:50'),
('70d5acf3-2d43-7ebb-9a90-67245e8b283e', 'Phan Giao Hưởng', '71pk/5i1bR0GhkKT6fAK5w==', 'Abel.Larose63@nowhere.com', 'Bình Dương', '0985492403', 'R2', 'Nữ', '2E7JS8SDNZ3196B32JVJ33', '1970-01-01 00:13:12', NULL),
('7136099c-206b-1466-81dd-867949feb8b5', 'Phan Quảng Thông', 'xMC1+yMZpgYErUV0kI90Mg==', 'LaurenaSibley@example.com', 'Thái Bình', '0983529887', 'R2', 'Nam', '654', '1970-01-01 00:00:51', '1970-01-01 02:13:50'),
('71c459c3-508d-1245-b6db-e5d54223c257', 'Phan Sơn Trang', 'Zo7LKcixJ/w35bbhoUcueg==', 'Ali_Q_Abbott12@nowhere.com', 'Quảng Ninh', '0982229481', 'R3', 'Nữ', '092IKWN274VHS11AEVXOLF2JFPEF', '1990-09-13 10:17:16', '1987-09-07 15:26:01'),
('72ce912f-6015-2e14-fb17-7000f455f3d5', 'Dương gọc Lâm', 'Bl4uLERSDF74LY/+fRa8cw==', 'kolwfbu5952@example.com', 'Hà Giang', '0988973071', 'R3', 'Nữ', 'XW24', '1993-06-23 13:47:16', '2019-06-17 09:24:15'),
('7325f44f-127c-240c-afdb-e5d54223c257', 'Phan Hiền Mai', '+K7vWtwRcq+ujPXOWPOBFw==', 'LourdesAbraham@example.com', 'Hải Dương', '0985671170', 'R1', 'Nữ', '983', '1998-08-12 17:16:50', '1970-01-01 00:14:47'),
('73feb9c0-5258-209c-1280-e8e2a817c80e', 'Võ Xuân Thu', 'OIxq0otBTYs9wAURnZKSVw==', 'wscttm3@example.com', 'Hà Giang', '0982907307', 'R1', 'Nữ', 'KP2P1673315E15E82GV6QUF10', '1991-04-05 14:34:23', '2012-06-12 00:17:56'),
('74017ba6-559b-3426-8532-6a1673ffca7c', 'Hồ Tâm Hạnh', '+A0nDcqpMMXwfQoQqkbvnw==', 'AbigailBloom@example.com', NULL, NULL, 'R3', NULL, NULL, NULL, '1970-01-01 00:00:09'),
('756ac66d-5ca5-79ff-b9db-e5d54223c257', 'Phan Khánh Duy', '0odvOJ7OEmDODp9eZalfZw==', 'KimberlieAragon13@nowhere.com', 'Hà Giang', '0981963422', 'R1', 'Nữ', '8R1P4U6', '1999-05-10 18:38:36', '2010-07-08 04:43:54'),
('758f86f1-3af9-68b9-1763-eeb1d8ed8cef', 'Dương Thanh Tuấn', 'UCCyiLGOYsp4fD1111P6QQ==', 'Junior_FChin994@example.com', 'Hà Giang', '0982776849', 'R2', 'Nữ', '2Y5Z7K5PL9S5', '1990-03-07 17:02:25', '1977-04-28 05:53:56'),
('75fcbf6d-4e84-4cc4-9f90-67245e8b283e', 'Nguyễn An Tường', '3DqRwAXV26Z0Hv3ecME/yg==', 'Abel61@example.com', 'Hà Giang', '0985330056', 'R3', 'Nữ', '7K95845', '2013-02-25 12:37:33', '2009-02-14 07:21:44'),
('7623d42f-35f4-1ce5-987d-e8c757976496', 'Vũ Thành Long', 'q2DgoXFjfFYqJHxW3hOsXQ==', 'Newsome21@example.com', 'Hà Giang', '0988703886', 'R3', 'Nam', 'KJ88AJ71118K9291CAK98MAKR327GX76O30515FR6V21', '1995-09-24 06:09:35', '1970-01-01 02:25:46'),
('767111e6-3dbc-615a-0880-e8e2a817c80e', 'Đặng Niệm Nhiên', 'dHy7GgjYs7BK+VAIlJviUg==', 'Armstead@example.com', 'Hải Dương', '0986254662', 'R3', 'Nam', '7D10', '2023-01-24 13:31:43', '1970-01-01 00:43:29'),
('7686595d-16d5-33b3-0080-e8e2a817c80e', 'Ngô Công Phụng', 'LPmh03Or7eUJ1hc+6R94vQ==', 'Gutierrez73@example.com', 'Quảng Ninh', '0989243531', 'R2', 'Nam', 'V6N9SG2NVDS533QY504HS12T6S09DCX7JHN4N3U1P14UE720Y0KCZD65Y4N545K4X0R7Y67CRQ', '2021-12-08 20:03:12', '2008-03-23 05:33:01'),
('768f8e64-7d10-20c9-967d-e8c757976496', 'Nguyễn Ðình Phú', 'btmz6uguZEF8blnbEL+TYg==', 'xmhz1900@nowhere.com', 'Ninh Bình', '0987840093', 'R1', 'Nam', 'D76X', '1980-09-30 07:53:09', NULL),
('771e3dd1-42bb-2339-acdb-e5d54223c257', 'Trần Thành Sang', 'euqc4O7z3zZ7JQItpzHqig==', 'Tanner_Banuelos@example.com', 'Hải Dương', '0988175045', 'R3', 'Nam', '630QHR78VAERTYKRPQY', '2003-01-09 07:40:05', '1970-01-01 00:10:02'),
('773acde0-4741-351b-6992-08c864661f9c', 'Phan Thiên Lạc', 'djfEFuR8T8UBk1ibpihdiQ==', 'Genevieve_Mendoza9@nowhere.com', 'Ninh Bình', '0983314701', 'R3', 'Nữ', '1G83XJWJ633CWR62R7OKH4', '1979-06-15 17:40:48', '2010-03-08 11:20:49'),
('791b9e6b-6010-1e33-b0db-e5d54223c257', 'Ngô Tiểu Quỳnh', 'TT7T1kC77Zrj5+rc4VRZpg==', 'kthkuizh3830@nowhere.com', 'Hà Giang', '0988278519', 'R1', 'Nam', '49COHT06', '1970-01-01 00:00:10', '1990-10-25 20:32:45'),
('79fa8253-391f-4864-b2db-e5d54223c257', 'Huỳnh Nhật Hùng', 'q/hV/+OMjJDgnlmyM6UI6Q==', 'vfdpiabb_mjai@example.com', 'Quảng Ninh', '0989746562', 'R1', 'Nữ', '5IH4IYV1CPN', '1988-12-13 05:31:32', NULL),
('7abe18db-2b8a-5fcb-aedb-e5d54223c257', 'Võ Dạ Yến', 'pHWqMj0o0G1DejCaECGZxg==', 'Lavenia.Abraham@example.com', 'Thái Bình', '0989690933', 'R1', 'Nam', 'V48ISL250179R38MPYV08C06U2O886U75070BJ2', '1970-01-01 02:45:15', '1970-01-01 00:01:09'),
('7b808a79-129e-4370-0018-7000f455f3d5', 'Đặng Ân Lai', 'L9s/0dx2FbvPHt57zIe2Ow==', 'wwmmm3222@nowhere.com', 'Hà Giang', '0980222404', 'R1', 'Nam', '10DE54BG3P543NOE790689980L68DWWC3N6AA9CPR7TY88C65CS79LZM4TZO2C6VYEVDTZUY1', '1997-07-02 09:38:53', NULL),
('7bec5682-21c4-666f-a8db-e5d54223c257', 'Lê Thanh Hiếu', 'IuShTOK1LQkdysgnirPpWw==', 'Rich.F_Hutchins@example.com', 'Thái Bình', '0983315968', 'R3', 'Nam', 'LO0UKL5814IX1O71ZC96A98Z8S9IGU6O50U1I2WB6AE29XV6TP3IT330811X15M0B4QEAX', '1970-01-01 00:00:01', '1970-01-01 00:01:06'),
('7d663944-7eb7-7c68-8add-867949feb8b5', 'Đặng Thy Khanh', 'CbBzmwXNs3gILMJEbV/V+w==', 'Adcock9@example.com', 'Hà Nội', '0983037219', 'R3', 'Nữ', 'MA', '2017-08-30 02:30:57', '1987-11-01 16:38:00'),
('7dbdf5fd-6a92-497b-0c80-e8e2a817c80e', 'Lê Ân Lai', 'Wf72YNxETU2zDm8XQgiWhQ==', 'Stpierre@example.com', 'Hà Giang', '0987202388', 'R3', 'Nam', 'XB263V0P519EJ1', '1997-07-11 23:03:24', '1975-05-14 02:56:23'),
('7e4a64ed-3925-5bb5-6392-08c864661f9c', 'Võ Thanh Bình', 'BJZqOQF8gz7VbOwGGaaP6A==', 'Isaacs9@example.com', NULL, NULL, 'R1', NULL, NULL, NULL, '1995-02-23 20:40:18'),
('7e8f50b2-5100-74d8-0480-e8e2a817c80e', 'Lê Tùng Linh', 'Jiyi6asxGbkN4MGUsyG7MA==', 'Aiken@example.com', 'Hải Dương', '0981845714', 'R1', 'Nam', 'A20584G8ZB8V', '1984-11-18 12:46:43', '2002-09-25 01:48:00'),
('7f3d5027-1858-6752-1080-e8e2a817c80e', 'Nguyễn Diễm Chi', 'dF7+cs2VZp022lu1v9jj+w==', 'Cordell_Sherrod995@example.com', 'Thái Bình', '0981678259', 'R2', 'Nam', 'H7068KAP5J80R', '2020-04-10 21:49:49', '1970-01-01 02:21:45'),
('7f4552ee-20f2-2f82-9890-67245e8b283e', 'Phan Mai Hương', 'v9kmsbN3L95l1q3yQiOcWg==', 'Aponte@nowhere.com', 'Bình Dương', '0983257387', 'R3', 'Nữ', 'L5528Z2XI65493', '1993-04-06 14:39:29', NULL),
('7f609b3d-31d7-548b-0318-7000f455f3d5', 'Huỳnh Ân Lai', 'SIvEy/LH/X8eTCG2xmUDew==', 'Adrian_Jaramillo@nowhere.com', 'Bình Dương', '0989630774', 'R3', 'Nam', '162QO60147493N0ICI8DDE9S6DUZE700WMYP7J2C3YY71MMB', '1970-01-01 00:12:00', '1990-06-06 02:26:39'),
('7f662b42-535c-433b-6c92-08c864661f9c', 'Trần ến Dũng', 'UsSR3Q1iGgdDDs3Sj7gQ+A==', 'Pierson@nowhere.com', 'Ninh Bình', '0980931014', 'R3', 'Nam', '7P2D67V65H9S6X2V16952S2', '1987-08-08 21:59:43', '1991-08-18 00:41:50');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;